languageCode = "en"
languageName = "English"
weight = 1
title = "Aristonous"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "Aristonous"
image = "IMG_3225.jpg"
headline = "A true philosopher"
bio = "Philosopher that wants to be a sage, polymath & erudite"